---
- hosts: all-masters
  sudo: yes
  sudo_user: seqware
  gather_facts: no
  tasks:
  - shell:  /home/seqware/bin/seqware workflow report --accession {{bwa_workflow_swid} | grep -A 4 -B 1 running| perl -e 'my $swid; my $dir; my $id; while(<>) { if (/Workflow Run SWID\s+\| (\d+)/) { $swid=$1 } if (/Workflow Run Working Dir\s+\| (\S+)/) { $dir=$1 } if (/Workflow Run Engine ID\s+\| (\S+)/) { $id=$1; print "seqware workflow-run cancel --accession $swid\n"; } }'
    register: scripts_commands
  - name: Run the cancel commands
    command: "{{item}}"
    with_items: scripts_commands.stdout_lines
  - name: Pause for 30 seconds
    pause: seconds=30
  - name: Copy perl script to host
    get_url: url=https://raw.githubusercontent.com/SeqWare/seqware-sandbox/develop/seqware-oozie-restart/seqware-oozie-retry.pl dest=/tmp/seqware-oozie-retry.pl
  - name: Generate restart script commands
    shell: /home/seqware/bin/seqware workflow report --accession {{bwa_workflow_swid}} | grep -A 4 -B 1 cancelled | perl -e 'my $swid; my $dir; my $id; while(<>) { if (/Workflow Run SWID\s+\| (\d+)/) { $swid=$1 } if (/Workflow Run Working Dir\s+\| (\S+)/) { $dir=$1 } if (/Workflow Run Engine ID\s+\| (\S+)/) { $id=$1; print "perl /tmp/seqware-oozie-retry.pl $dir $id $swid\n"; } }'
    register: restart_commands
  - name: Run the retry commands
    command: "{{item}}"
    with_items: restart_commands.stdout_lines
  - name: Delete the retry perl script
    file: path=/tmp/seqware-oozie-retry.pl state=absent
~                                                             
