---
- include: db.yml
- hosts: demo
  sudo: True
  vars: 
    welcome: Would you kindly checkout
  tasks:
  - hostname: name=demo
  - name: ensure maven is installed
    apt: name=maven state=installed update_cache=yes cache_valid_time=3600
  - name: ensure git is installed
    apt: name=git state=installed update_cache=yes cache_valid_time=3600
  - name: ensure cowsay is installed
    apt: name=cowsay state=installed update_cache=yes cache_valid_time=3600

  - name: Add JRE ppa
    apt_repository: repo="deb http://ppa.launchpad.net/webupd8team/java/ubuntu precise main" state=present
  - name: Automatically select the Oracle License
    shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections

  - name: Install JRE
    apt: pkg=oracle-java7-installer state=latest update-cache=yes force=yes

  - name: Template motd
    template: src=00-header.j2 dest=/etc/update-motd.d/00-header

#- hosts: demo
#  sudo: True
#  roles:
  #    - {role: java, java_provider: Cloudera}


#- hosts: demo
#  sudo: True
#  roles:
  #    - {role: Ansibles.perl}


  - name: Register any killed states?
    shell: dmesg | grep "killed"
    register: killed_msg
    failed_when: '"killed" in killed_msg.stdout' 
    changed_when: false


  - name: Create cowsay dmesg
    shell: creates=cowsay.dmesg.out dmesg | cowsay > cowsay.dmesg.out
